// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJLKTMeexUaqmYPfH4gXrQqvDkKG3RZE',
    appId: '1:344971395973:web:f03072bbc80634d1b6baec',
    messagingSenderId: '344971395973',
    projectId: 'chattingapp-a0abb',
    authDomain: 'chattingapp-a0abb.firebaseapp.com',
    storageBucket: 'chattingapp-a0abb.appspot.com',
    measurementId: 'G-PR090KP3K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8A4fX4LL9Kn9HrLZ_hiHr2NMJTcwEhCY',
    appId: '1:344971395973:android:b7ba885cca1ad5f7b6baec',
    messagingSenderId: '344971395973',
    projectId: 'chattingapp-a0abb',
    storageBucket: 'chattingapp-a0abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUansJd2MmEPPmJH8zNweqcfzDLAiDqPQ',
    appId: '1:344971395973:ios:fca1cc7dc86a2795b6baec',
    messagingSenderId: '344971395973',
    projectId: 'chattingapp-a0abb',
    storageBucket: 'chattingapp-a0abb.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUansJd2MmEPPmJH8zNweqcfzDLAiDqPQ',
    appId: '1:344971395973:ios:fca1cc7dc86a2795b6baec',
    messagingSenderId: '344971395973',
    projectId: 'chattingapp-a0abb',
    storageBucket: 'chattingapp-a0abb.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArJLKTMeexUaqmYPfH4gXrQqvDkKG3RZE',
    appId: '1:344971395973:web:c13baafc8b4cea67b6baec',
    messagingSenderId: '344971395973',
    projectId: 'chattingapp-a0abb',
    authDomain: 'chattingapp-a0abb.firebaseapp.com',
    storageBucket: 'chattingapp-a0abb.appspot.com',
    measurementId: 'G-VDVMQ0RFCM',
  );
}
